name: Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "*.ini"
      - "*.md"
      - "**/*.txt"
      - ".gitignore"
      - ".gitmodules"
      - ".gitattributes"
      - ".editorconfig"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "*.ini"
      - "*.md"
      - "**/*.txt"
      - ".gitignore"
      - ".gitmodules"
      - ".gitattributes"
      - ".editorconfig"
jobs:
  build:
    name: ${{ matrix.runner }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        runner: [macos-latest, ubuntu-latest, windows-latest]
        architecture: [x64]
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
      runner: ${{ matrix.runner }}
      architecture: ${{ matrix.architecture }}
      build-distribution: ${{ matrix.runner == 'ubuntu-latest' && matrix.python-version == '3.13' }}
